### ISSUE TITLE
unable to build on vmhgfs (VMware shared folder)

### ISSUE THREAD

**Issue by SecsAndCyber** [Cisco-Talos/pyrebox#12]
Reproduction steps:
* Share NTFS folder from Windows host to Ubuntu VM with VMware Workstation
* `cd /mnt/hgfs/shared`
* `git clone https://github.com/Cisco-Talos/pyrebox.git`
* `cd pyrebox`
* `./build.sh`

>[\*] Patching qemu...
>ln: failed to create symbolic link ‘qemu/pyrebox’: Operation not supported
>[\*] Configuring qemu...
>ln: failed to create symbolic link ‘linux-headers/asm’: Operation not supported
>ln: failed to create symbolic link ‘i386-softmmu/Makefile’: Operation not supported
>ln: failed to create symbolic link ‘x86_64-softmmu/Makefile’: Operation not supported
>[\!] Oops... build failed!

**Comment by xabiugarte** [comment]
Symbolic links seem to be a recurrent problem for VMWare shared directories between different operating systems. Since QEMU (and PyREBox) require symbolic link creation for the build process, I recommend building it in a directory different from the hgfs shared folder. I am leaving the issue open to document the limitation, keep track of it, and provide additional info in case we find a solution.

**Comment by xabiugarte** [comment]
Closing this issue
