### ISSUE TITLE
win32 file creation/deletion tracking

### ISSUE THREAD

**Issue by mdcrtse** [Cisco-Talos/pyrebox#14]
I am interested in tracking the creation/deletion of files in a win32 guest, similar to the process create/delete tracking that is done in the script_example.py script.  Is there a way to do that?

**Comment by xabiugarte** [comment]
PyREBox does not support that feature currently, as part of its VMI component. Nevertheless, you can monitor API calls in order to capture this behavior. If you are tracing a user mode program, you can, for example, trace the execution of functions NtCreateFile, NtOpenFile, NtDeleteFile, NtWriteFile, NtReadFile in ntdll.dll. Those are the lowest level functions you can trace in user-land, and your program may probably end up calling them for manipulating files.

You will need to fetch the address for these functions using the PyREBox API, and then set breakpoints or instruction callbacks on those addresses. 

Once the function is called, you will need to read the function parameters. The value referencing the file will be a file handle. At that point, you can use volatility in order to retrieve, for example, the file name associated to the handle.

I hope this helps with your question.
