### ISSUE TITLE
Starting new process

### ISSUE THREAD

**Issue by takadito15** [Cisco-Talos/pyrebox#15]
Hi

Is it possible to launch new process inside the vm? 
Are there any options except launching it manually via VNC?

Tnx

**Comment by xabiugarte** [comment]
Hi!

Currently there is no functionality in PyREBox in order to automate the execution of binaries inside the guest, but it is one the features in the road-map. There are, anyway, several options:

* Deploying an agent (can be as simple as a batch or python script) that waits until a USB is attached, containing the binary to run and executes the sample as soon as it is available.
    - For this, you should create a usb image and then attach it to the VM using QEMU commands, such as usb_add.
* Sending keystrokes to the VM to emulate an interaction that runs the sample.


I am leaving this issue opened, and will update it as soon as we add this functionality to PyREBox.

**Comment by xabiugarte** [comment]
Hi @takadito15, a guest agent has been developed in order to deal with sample execution automation. You can check the related documentation (https://pyrebox.readthedocs.io/en/latest/guest_agent.html). 

For the moment it support Windows 32 and 64 bits. Linux support will come soon. I am leaving this issue open until Linux support is implemented.

**Comment by xabiugarte** [comment]
Linux support has been already implemented. I am closing this issue now.
