### ISSUE TITLE
Trace process memory read & write events (user space)

### ISSUE THREAD

**Issue by takadito15** [Cisco-Talos/pyrebox#21]
Hi,

Is it possible to monitor user space memory read and write events per process?
I would like to generate memory reference trace for specific process, something similar to the one created by Pin tool: [https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/index.html#MAddressTrace](https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/index.html#MAddressTrace)

Thanks

**Comment by xabiugarte** [comment]
Hi!

Yes, it is possible. As you may have experienced, by default, memory read/write callbacks are triggered for every process and memory address. This is a result of how the memory read/write instrumentation works internally. In order to avoid entering into the python code on every memory read/write for every process (high overhead), there is a feature called triggers. Triggers are c/c++ code snippets that are compiled as shared libraries and loaded dynamically whenever needed. A trigger must declare a function that will be called on every callback, just before the control is passed to the python callback. This function can decide whether to pass the callback to python or to return immediately avoiding the python overhead. PyREBox also allows to pass variables from your python script to the trigger, and vice-versa (but this requires to understand a bit about interfacing Python and C code).

The following script shows an example of how to initialize a memory write callback that is only triggered for an specific process, for memory writes that occur in a given memory address range:

https://github.com/Cisco-Talos/pyrebox/blob/master/scripts/mem_write_test.py#L66

That said:

There is a much simpler breakpoint API:

b = api.BP(0x00000000,pgd,size=0x80000000,typ=BP.MEM_WRITE)

This BP class uses the same *trigger* mechanism under the hood. Currently, the BP class just starts a shell whenever the breakpoint is hit, but I have realized that your case will certainly be a common use case. I will add a parameter to the BP class to allow passing a python function as a callback instead of starting a shell.

I am leaving this issue open to track the status of the aforementioned enhancement.

Thanks!

**Comment by xabiugarte** [comment]
Hi,

Commit f8634abf283c601961e99799a2222a359ceb8fdf contains a modification for the BP class that allows to set up per/process memory read/write callbacks in an easier way. The script https://github.com/Cisco-Talos/pyrebox/blob/master/scripts/mem_write_breakpoint_test.py#L96 shows an example of how to use it.

I am closing the issue, please reopen it if you still have any comments.
