### ISSUE TITLE
Question: Dynamically add MEM_READ_CB?

### ISSUE THREAD

**Issue by bridgeythegeek** [Cisco-Talos/pyrebox#26]
I'm trying to add a `MEM_READ_CB` callback once a named process has started.

The new process is detected via `CREATEPROC_CB` and, as per the below, I see the `Matched new process!` message:
```
# Called via: cm.add_callback(CallbackManager.CREATEPROC_CB, new_proc, name="new_proc")
def new_proc(pid, cr3, name):
    global cm
    if name == 'WINSLL.EXE':
    	pyrebox_print("Matched new process! pid=%d, cr3=%d, name=%s\n" % (pid, cr3, name))
    	cm.rm_callback('new_proc')
    	cm.add_callback(CallbackManager.MEM_READ_CB, mem_read, name="mem_read")

def mem_read(cpu_index, vaddr, size):
	global cm
	pyrebox_print("READ! vaddr=%d, size=%d" % (vaddr, size))
	cm.rm_callback("mem_read")
```

The code seems fine in that there are no errors, but the `mem_read` function is seemingly never called, or at least, I never see my `READ` message.

Am I missing something? Is it essential to add a `cm.add_trigger("mem_read", "triggers/trigger_bpr_memrange.so")` trigger? I don't want to because I want *any* read.

Thanks!

**Comment by xabiugarte** [comment]
Hi,

Memory read and write callbacks are **triggered for all the monitored processes**, so I think you are missing a call to the api in order to monitor the target process:

https://pyrebox.readthedocs.io/en/latest/api.html#api.start_monitoring_process

Your code should be like:

```
# Called via: cm.add_callback(CallbackManager.CREATEPROC_CB, new_proc, name="new_proc")
def new_proc(pid, cr3, name):
    global cm
    if name == 'WINSLL.EXE':
    	pyrebox_print("Matched new process! pid=%d, cr3=%d, name=%s\n" % (pid, cr3, name))
    	cm.rm_callback('new_proc')
    	cm.add_callback(CallbackManager.MEM_READ_CB, mem_read, name="mem_read")
        api.start_monitoring_process(cr3)

def mem_read(cpu_index, vaddr, size):
	global cm
	pyrebox_print("READ! vaddr=%d, size=%d" % (vaddr, size))
	cm.rm_callback("mem_read")
```

The documentation explains how each callback type is triggered: https://pyrebox.readthedocs.io/en/latest/scripting.html#memory-read

Most of them are only triggered for monitored processes, but others work in a different way (such as VMI callbacks, that are triggered globally, or insn_begin, that is triggered no matter if the process is monitored or not when a specific pgd and address are specified when setting the callback).

Finally, you might also be interested in using breakpoints, which are, after all, a wrapper around the callback interface for instruction execution and memory read/write. Breakpoints allow to set a wide memory range such as 0x00000000-0xFFFFFFFF. The following closed issue (https://github.com/Cisco-Talos/pyrebox/issues/21) gives some info about this, and there are example scripts. 

I am closing this issue, please reopen it if you have any additional questions.

Hope it helps,
