### ISSUE TITLE
Execution related callbacks can be triggered for wrong PGD

### ISSUE THREAD

**Issue by f4rnham** [Cisco-Talos/pyrebox#34]
Execution related callbacks (BLOCK_BEGIN_CB, BLOCK_END_CB, INSN_BEGIN_CB, INSN_END_CB) can be triggered for pgd other than specified in `cm.add_callback` call.

Tested under Win7SP1x86, see test script.
https://github.com/f4rnham/pyrebox/blob/pgd_mismatch/scripts/block_end_test.py

My assumption is, that certain translation blocks are shared between processes. TB hashing (tb_hash_func) doesn't take CR3 / PGD into account and optimizations in emulated OS could result in a single ntdll.dll/kernel32.dll/... copy in physical memory being mapped into multiple processes.

Currently, callbacks are added into TBs during their translation based on currently executing pgd. This can result in TB being created (first time executed) by non-monitored process (without callback) and later reused by monitored process and missing callback trigger.

While I can't confirm the last part by test, based on my understanding of PyREBox it could occur.

**Comment by xabiugarte** [comment]
Hi f4rnham,

You are correct. I really appreciate you found this problem. I have already implemented a solution that should fix this issue by:

* Inserting the callbacks in translated blocks regardless of the PGD.
* PGD checking is done at callback delivery time.

This may introduce a small overhead, but we need to live with that. Another possibility would be to change TB hashing to include the address space in the input data, but that would also probably impact performance. Also, one of the premises of this project is to keep the set of QEMU modifications minimal to allow upgrading the tool to new versions of QEMU easily, so I just preferred to modify the pyrebox-side of the code, instead of the QEMU side.

I am taking some time to test this fix, as it affects to the core of pyrebox, and will merge it soon.

Again, thank you very much for pointing this out.

**Comment by xabiugarte** [comment]
This problem should have been fixed in the last commit (ce32f2a4e20fc9c6538a4d7095586c00f480e945), which also adds module load/remove detection, which I was working on.
