### ISSUE TITLE
Question: Current instruction for MEM_READ_CB/MEM_WRITE_CB?

### ISSUE THREAD

**Issue by bridgeythegeek** [Cisco-Talos/pyrebox#44]
Working in 64-bit.

After breaking on a `MEM_READ_CB` or `MEM_WRITE_CB`, I would like to know the memory address of the instruction that caused the read or write.

I know I could read `cpu.RIP`, but that gives me the value of the _next_ instruction, which is of course not the same thing.

I considered the `Instruction Register` which might have been enough, but I couldn't find that exposed through the API(??).

So, is there any way of knowing the address of the current instruction being executed when a `MEM_READ_CB` or `MEM_WRITE_CB` breaks?

Thanks!

**Comment by xabiugarte** [comment]
Hi Bridgey,

I am in the process of adding this feature. As you may have  observed, there were some breaking changes in the last commits, in which read/write memory callbacks were moved to the end of the instruction.

Since this may require another change in the API, I am trying to decide which is the best way to deal with these API changes in general.

I will likely add versioning to the API and callback parameters, so that I can make changes in the future without breaking user scripts. In this new version, callback parameters will be passed as **kwargs parameters, instead of individual parameters, facilitating changes in the future.

As you suggest, I will add the "pc" and "next_pc" arguments to every callback happening at the end of an instruction/block: opcode_range, mem read/write, insn_end, and block_end.

This development is in progress, so I will notify you through this thread as soon as it is available.

Thanks for your suggestions / issues!

Regards,

Xabier

**Comment by xabiugarte** [comment]
Hi Bridgey,

The answer I gave you was not completely accurate. I was confused by your question and the fact that there had been some changes in the MEM_WRITE callback. 

The MEM_WRITE callback is delivered *after* the memory write has been produced. This means that when the callback is triggered, it is possible to read the *new* value for memory by using the api.

Nevertheless, the EIP/RIP register in the cpu object points to the instruction that produced the memory write, not the next instruction, so you can read the RIP from the cpu object.

Nevertheless, this doesn't change the fact that I will introduce some changes on the callback format, to allow the addition of new parameters on callback functions without breaking backwards compatibility. Since this requires to modify all the scripts, I will maintain the old style with positional arguments (default), and create a new style (dictionary with keyword-value parameters), that will be optional to use. I have created an issue to track the status and problems about this new interface (https://github.com/Cisco-Talos/pyrebox/issues/48).

I am closing this issue now, please let me know if you have any problems, or reopen this issue if necessary.

Thanks,

Xabier
