### ISSUE TITLE
OPCODE_RANGE_CB Callback not catching "0x0F" opcode

### ISSUE THREAD

**Issue by Bondey** [Cisco-Talos/pyrebox#51]
I'm messing around with a module to bypass some anti-VM tricks and many of them depends on the instruction "CPUID" witch corresponds to the opcode "0x0FA2"
Example:
![captura de pantalla de 2018-05-24 17-38-50](https://user-images.githubusercontent.com/2705883/40532546-1aa7fa9e-6000-11e8-9d4a-6d36dd31e9a8.png)

The question is that, with the callback OPCODE_RANGE_CB, many other opcodes like the "CALL" from the examples and some other random works perfect, but with this one it doesn't seem to catch nothing:

`cm.add_callback(CallbackManager.OPCODE_RANGE_CB,cpuid_call,start_opcode=0x0F,end_opcode=0x0F) #0FA2 -> CPUID`

i'm using Win7x86 and the tool Pafish (https://github.com/a0rtega/pafish) to make tests~~

**Comment by xabiugarte** [comment]
Hi Bondey,

This is due to the way how multi-byte opcodes are dealt with in the translation routine. So far, PyREBox only considers 1 byte (and in this case, it would be the second byte). It should work if you use the 0xa2 byte instead of 0x0f, but take into consideration that it might overlap other opcodes and you will need to reassure that it is a cpuid instruction by reading a couple of bytes starting at the program counter:

Something like:

if api.r_va(pgd, pc, 2) == "\x0f\xa2":
    #treat the cpuid instruction.



In any case, I am marking this issue as bug/enhancement, and self-assigning it, as this can definetely be improved to support multi-byte opcodes properly. It requires certain changes in the instrumentation code but it is definitely doable.

I am leaving the issue open, and will update/close it when the new functionality is ready.

Thanks for reporting this!

**Comment by xabiugarte** [comment]
Merged to master.

Thanks!
