### ISSUE TITLE
VM not starting (Am I missing something?)

### ISSUE THREAD

**Issue by Shockmeister** [Cisco-Talos/pyrebox#55]
Hi,

After creating the image using:

qemu-img create -f qcow2 -o compat=0.10 images/Win7.qcow2 30G

I then ran the following to create the VM:

./pyrebox-x86_64 -m 2g -monitor stdio -usb -drive file=images/Win7.qcow2, index=0,media=disk,format=qcow2,cache=unsafe -cdrom images/Win7.iso -boot d -enable-kvm

This returns the qemu prompt, but the VM does not start up.

Am I missing something?

Thanks!

**Comment by xabiugarte** [comment]
Hi!

By default, PyREBox is compiled **only** with VNC support. You can connect to the screen of the VM by using any VNC client. For this, you may need to configure vnc via command line parameters (see start_i386.sh as an example). If you want an actual window to pop up (the screen of the VM), you need to recompile pyrebox. You can follow the instructions here:

https://github.com/Cisco-Talos/pyrebox/issues/39

Hope this helps, and of course, feel free to reopen the bug if you still have any problem.

Regards,

Xabier

**Comment by Shockmeister** [comment]
Thank you  so much!

**Comment by johnzion** [comment]
Hello, i have the same problem ,well

qemu-img create -f qcow2 -o compat=0.10 Win7.qcow2 40G


(pyrebox_venv) root@ubuntu:/home/pyrebox/pyrebox# ./pyrebox-x86_64 -m 256 -monitor stdio -usb -drive file=Win7.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom /home/pyrebox/Downloads/de_windows_7_professional_with_sp1_x64_dvd_u_676919.iso -boot d -enable-kvm -conf pyrebox.conf.Win7SP0x64 





[*] Loading python component initialization script
[*] Platform: x86_64-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf.Win7SP0x64'
[*] Searching for KDBG...
[*] Initializing scripts...
[*]  Loading python module scripts.script_example
[*]  Loading python module plugins.guest_agent
[plugins.guest_agent] [*]    Initializing guest_agent plugin
[!] Could not initialize agent, offset config file missing!
[scripts.script_example] [*]    Initializing callbacks
[scripts.script_example] [*]    Initialized callbacks
[*]  Loading python module scripts.script_example_min
[scripts.script_example_min] [*]    Initializing callbacks
[scripts.script_example_min] [*]    Initialized callbacks
[*]  Loading python module scripts.vol_test
[!] Could not initialize python module due to exception
    No module named vol_test
[*]  Loading python module scripts.proc_bp
[!] Could not initialize python module due to exception
    No module named proc_bp
[*]  Loading python module scripts.mem_write_test
[scripts.mem_write_test] [*]    Initializing callbacks
[scripts.mem_write_test] [*]    Initialized callbacks
[*]  Loading python module scripts.getset_var_example
[scripts.getset_var_example] [*]    Initializing callbacks
[scripts.getset_var_example] [*]    Initialized callbacks
[*]  Loading python module mw_monitor.mw_monitor
[*]  Module plugins.guest_agent already imported, did you want to reload it instead?
[mw_monitor.mw_monitor] Reading mw_monitor configuration...
[!] Could not initialize python module due to exception
    [Errno 2] No such file or directory: 'mw_monitor_run.json'
[*]  Loading python module pyrebox_test.test_0_vmi_create_proc
[pyrebox_test.test_0_vmi_create_proc] [*]    Initializing callbacks
[pyrebox_test.test_0_vmi_create_proc] [*]    Initialized callbacks
[*] Finished python module initialization
QEMU 2.12.0 monitor - type 'help' for more information
(qemu) VNC server running on 127.0.0.1:5900

[SLEUTHKIT]
Opening image - Size: 42949672960
[!] Error, could not open volume system
Cannot determine partition type

[SLEUTHKIT]
Opening image - Size: 3268147200
[!] Error, could not open volume system
Cannot determine partition type

**Comment by xabiugarte** [comment]
> Hello, i have the same problem ,well
> 
> qemu-img create -f qcow2 -o compat=0.10 Win7.qcow2 40G
> 
> (pyrebox_venv) root@ubuntu:/home/pyrebox/pyrebox# ./pyrebox-x86_64 -m 256 -monitor stdio -usb -drive file=Win7.qcow2,index=0,media=disk,format=qcow2,cache=unsafe -cdrom /home/pyrebox/Downloads/de_windows_7_professional_with_sp1_x64_dvd_u_676919.iso -boot d -enable-kvm -conf pyrebox.conf.Win7SP0x64
> 
> [_] Loading python component initialization script [_] Platform: x86_64-softmmu
> [_] Starting python module initialization [_] Reading configuration from 'pyrebox.conf.Win7SP0x64'
> [_] Searching for KDBG... [_] Initializing scripts...
> [_] Loading python module scripts.script_example [_] Loading python module plugins.guest_agent
> [plugins.guest_agent] [_] Initializing guest_agent plugin [!] Could not initialize agent, offset config file missing! [scripts.script_example] [_] Initializing callbacks
> [scripts.script_example] [_] Initialized callbacks [_] Loading python module scripts.script_example_min
> [scripts.script_example_min] [_] Initializing callbacks [scripts.script_example_min] [_] Initialized callbacks
> [_] Loading python module scripts.vol_test [!] Could not initialize python module due to exception No module named vol_test [_] Loading python module scripts.proc_bp
> [!] Could not initialize python module due to exception
> No module named proc_bp
> [_] Loading python module scripts.mem_write_test [scripts.mem_write_test] [_] Initializing callbacks
> [scripts.mem_write_test] [_] Initialized callbacks [_] Loading python module scripts.getset_var_example
> [scripts.getset_var_example] [_] Initializing callbacks [scripts.getset_var_example] [_] Initialized callbacks
> [_] Loading python module mw_monitor.mw_monitor [_] Module plugins.guest_agent already imported, did you want to reload it instead?
> [mw_monitor.mw_monitor] Reading mw_monitor configuration...
> [!] Could not initialize python module due to exception
> [Errno 2] No such file or directory: 'mw_monitor_run.json'
> [_] Loading python module pyrebox_test.test_0_vmi_create_proc [pyrebox_test.test_0_vmi_create_proc] [_] Initializing callbacks
> [pyrebox_test.test_0_vmi_create_proc] [_] Initialized callbacks [_] Finished python module initialization
> QEMU 2.12.0 monitor - type 'help' for more information
> (qemu) VNC server running on 127.0.0.1:5900
> 
> [SLEUTHKIT]
> Opening image - Size: 42949672960
> [!] Error, could not open volume system
> Cannot determine partition type
> 
> [SLEUTHKIT]
> Opening image - Size: 3268147200
> [!] Error, could not open volume system
> Cannot determine partition type

Could you please another issue for this? It seems unrelated to the original issue, that was already closed. Also, please specify if you observe the system booting up even after the error:

"""[!] Error, could not open volume system"""
