### ISSUE TITLE
Question:Snapshot at the beginning  and load snapshot at the end

### ISSUE THREAD

**Issue by dmbjzhh** [Cisco-Talos/pyrebox#59]
Hi pyrebox developers,

I am working on a project that needs to take a snapshot at the beginning of the VM, then use Guest Agent to run a malware and call my own function to analyze the memory state, finally when analyze is over, load the initial snapshot to recover VM. So, I use api.save_vm in initialize_callbacks() and api.load_vm in clean(), and set scripts.my_script:True in pyrebox.conf.

The problem is when I start VM in pyrebox, it always reports:"pyrebox-i386: -drive file=images/WinXP.qcow2,index=0,media=disk,format=qcow2,cache=unsafe: No block device can accept snapshots".

However, when the VM start completely and then I manually use qemu command "import_module my_script", the script works well. It can take a snapshot when use command "import_module", and  load the initial snapshot when use command "unload_module".

But, I wonder is there a way to take and load snapshot automatically in the script instead of type commands to call my script manually every time?

Thanks a lot.

**Comment by xabiugarte** [comment]
Hi,

It looks like the block device may not be initialized at the moment when you are trying to save a snapshot.

The way I usually do what you are trying to achieve, is the following:
(1) I just boot the machine manually (do not load any pyrebox plugin), and save a clean snapshot in which the guest agent is running and ready to accept files.
(2) In order to start my analysis, I boot again the machine, providing an additional command line option to pyrebox: "-loadvm snapshot_name". This command line option will first load the snapshot (the clean one, you previously saved), and then will load any pyrebox plugins you may have configured. In this way, your pyrebox plugins do not need to deal with snapshot management at all.

Hope this helps! Please reopen the issue if you are still having trouble.
