### ISSUE TITLE
Problems running API tracer

### ISSUE THREAD

**Issue by dmbjzhh** [Cisco-Talos/pyrebox#64]
Hi pyrebox developers:

I am using api_tracer to extract the apis commonly used by malware.
When I run the calculator on a WinXP VM, the calculator runs normally and api_tracer gets function_calls.log. 
But when I run Wannacry.exe, Wannacry.exe will automatically quit after running. I unload the mw_monitor module and re-run Wannacry.exe, it can successfully encrypt the files in the virtual machine.
![mw_monitor_problem1](https://user-images.githubusercontent.com/9897372/47404220-12247e00-d77f-11e8-9813-af8d0be169a1.png)

Another ransomware is "Trojan-Ransom.Win32.Jaff.exe", its MD5 is "d349764bd5e16ee0e202b1e9dc057318", just like wannacry, it can also encrypt files in computers. When I use mw_monitor to monitor Jaff.exe's execution, unlike wannacry, Jaff.exe does not end the process, but it is stuck and doesn't have any movement, but the virtual machine can still operate normally.
![mw_problem_jaff](https://user-images.githubusercontent.com/9897372/47404273-3aac7800-d77f-11e8-9b74-1a6e2b62dae5.png)

My mw_monitor configuration files as follow:
mw_monitor.conf:
```
[general]

output_bundle: bundle.tar.gz
api_database: mw_monitor/third_party/deviare2_db/deviare32_populated.sqlite

[interproc]
bin_log_name: interproc.bin
text_log_name: interproc.log
basic_stats_name: basic_stats

[api_tracer]
text_log_name: function_calls.log
bin_log_name: function_calls.bin

[coverage]
cov_log_name: coverage.bin
cov_text_name: coverage.log

[dumper]

path = dumper/
```

mw_monitor_run.json:
```
{
    "api_tracer": {
        "bin_log": false,
        "exclude_apis": [],
        "exclude_modules": [],
        "exclude_origin_modules": [],
        "include_apis": [],
        "light_mode": true,
        "procs": null,
        "text_log": true
    },
    "coverage": {
        "procs": null
    },
    "dumper": {  
        "dump_at": "kernel32.dll!CopyFileA",
        "dump_on_exit": false
    },
    "general": {
        "files_path": "C:\\",
        "main_executable": "wannacry.exe",
        "files_bundle": "malware/malware.zip"
    },
    "interproc": {
        "basic_stats": true,
        "bin_log": true,
        "text_log": true
    },
    "modules": {
        "api_tracer": true,
        "coverage": false,
        "dumper": false,
        "interproc": false
    }
}
```

**Comment by xabiugarte** [comment]
Hi dmbjzhh,

The latest commits on the master branch include a few improvements on symbol resolution:

- Extracting symbols from the filesystem instead of memory (using TSK). Sometimes some memory pages are missing: paged-out, not mapped into virtual memory, which makes difficult to parse the export tables from memory.
- Symbol caching. If a configuration option is added to pyrebox.conf (see examples in the master branch), symbols are saved from one execution to another. The cache file should be unique per installation, and you should not have to worry about ASLR, as we only store relative offsets with respect to the base of the DLL (as opposed to absolute offsets of API functions in a given run).

These two improvements should overall improve the performance of the plugin. Please try it, and in case it still does not work, please feel free to reopen this issue.

Xabier
