### ISSUE TITLE
agent question

### ISSUE THREAD

**Issue by johnzion** [Cisco-Talos/pyrebox#66]
Hello, 
well i would like to ask about the agent that its installed in Victim Vm.
Is it only for transfering the samples and to run python scripts?
Can i run python scripts without the agent?

Can i import the logs into elasticstack?

**Comment by xabiugarte** [comment]
Hi @johnzion,

Yes, the agent is only for transferring and running samples into the guest VM. You can perfectly run python scripts on PyREBox without installing the agent, as all the necessary information is extracted using VMI techniques from outside the operating system. No external component, agent, or driver, is necessary in the guest.

Nevertheless, you will need to copy and detonate the sample yourself.

Regarding elasticstack, there is no built-in support for it. Nevertheless, you may have observed that all the plugin output (that is printed through standard output in the qemu monitor) is done by calling a printer function. This printer function is initialized in the initialize_callbacks routine, and stored as a global variable.

All you would need to do in order to import these logs into elastic-stack is to wrap or replace this printer function by a python function you code yourself. In your function, you can format the messages properly and save/submit them anywhere. For instance, you could redirect these messages to a logstash service via the python logging interface:

https://stackoverflow.com/questions/48195759/how-to-configure-native-python-logging-library-with-logstash-and-elastic

I hope this answers your question. Feel free to re-open the issue or open a new one if you have other questions.

Thanks,

Xabier
