### ISSUE TITLE
unknown command: 'usb_add'

### ISSUE THREAD

**Issue by BrandonGDossantos** [Cisco-Talos/pyrebox#95]
I am trying to get the guest agent onto the guest machine, following this https://pyrebox.readthedocs.io/en/latest/quickstart.html#loading-a-usb-image-with-files. I was trying to do `usb_add` but I got `unknown command: 'usb_add'` and the command is not listed in `(qemu) help`. What is the issue?

Also, if my guest machine is 64 bit, does that mean I need to recompile the DeviareDb using Visual Studio for 64 bit to use API tracer? Is the sqlite database in the repo set for 32 bit?

**Comment by xabiugarte** [comment]
It seems that usb_add has been finally removed (see https://wiki.qemu.org/ChangeLog/2.11), and I should update the documentation. I'll open an issue to keep track of that myself. Please follow the indications available in the Qemu documentation in order to attach a USB device to the machine. 

Hi Brandon, 64 bit support for the API tracing has been under development on the mw_monitor2 plugin, a refined version of the original mw_monitor. The plugin has been tested only up to a certain point. It contains a 64bit database, but do not expect it to be super estable. I encourage you to use it and open issues if you find problems, but please be patient, as currently I am giving priority to python3 migration because the end of support is approaching.
